/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#7D8774",
        "outline-variant": "#D8D3C1",
        "primary": "#3B6C2B",
        "primary-container": "#4E7A3E",
        "on-primary-container": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#DCECD2",
        "primary-fixed-dim": "#B2D49F",
        "on-primary-fixed": "#0F240A",
        "on-primary-fixed-variant": "#274D1C",
        "inverse-primary": "#A3D491",
        "secondary": "#5A6F50",
        "secondary-container": "#E2EBD8",
        "on-secondary-container": "#1B2E17",
        "secondary-fixed": "#DCE8D4",
        "secondary-fixed-dim": "#BDCDB5",
        "on-secondary-fixed": "#142410",
        "on-secondary-fixed-variant": "#3E5136",
        "tertiary": "#7EB53F",
        "tertiary-container": "#EBF5DE",
        "on-tertiary-container": "#1E3B0B",
        "tertiary-fixed": "#8CBF41",
        "tertiary-fixed-dim": "#74A836",
        "on-tertiary-fixed": "#142707",
        "on-tertiary-fixed-variant": "#335B13",
        "accent-gold": "#E5A823",
        "accent-gold-container": "#FEF6DC",
        "accent-gold-on": "#6B4C00",
        "background": "#F7F4E9",
        "surface": "#FAF8F0",
        "surface-dim": "#E9E3D0",
        "surface-bright": "#FAF8F0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F4EFE1",
        "surface-container": "#EDE7D4",
        "surface-container-high": "#E6DFCB",
        "surface-container-highest": "#DED6C1",
        "surface-variant": "#E4DEC9",
        "surface-tint": "#4E7A3E",
        "inverse-surface": "#1B2E18",
        "inverse-on-surface": "#F5F0D3",
        "on-surface": "#1E2519",
        "on-surface-variant": "#4C5544",
        "on-background": "#1E2519",
        "error": "#C23B2A",
        "error-container": "#FDE8E5",
        "on-error": "#ffffff",
        "on-error-container": "#751508"
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace']
      }
    },
  },
  plugins: [],
}
